spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.1.4 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: root # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
    pool:
      max-active: 8
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8
      min-idle: 0

      # 主节点哨兵
      sentinel:
        # 主从配置
        # name of Redis server  哨兵监听的Redis server的名
        master: master
        # comma-separated list of host:port pairs  哨兵节点配置列表
        nodes: 192.168.0.165:26479, 192.168.0.165:26478, 192.168.0.165:26477

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.testweb.mall: info

logstash:
  host: 192.168.1.4