spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.1.4 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: root # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

# 异常等级
logging:
  level:
    root: info
    com.testweb.mall: debug

# 集成ELK
logstash:
  host: 192.168.1.4


#  在项目中查看半天没有找到有引用redis的地方
#  猜测是哪个东西里面引入了redis，然后做了redis的健康检查。解决方案如下，在application.yml中配置
#  禁止Actuator监控Redis连接
#management:
#  health:
#    redis:
#      enabled: false